services:
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: postgres:15
    container_name: auth-db
    env_file:
      - ./backend/auth-service/.env.db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
