services:
  auth-service:
    build: 
      context: ..
      dockerfile: ./auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - auth_network

  auth-db:
    image: postgres:15
    container_name: auth-db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

volumes:
  auth_db_data:

networks:
  auth_network:
    driver: bridge