pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // build docker image
                sh 'docker build -t storefront/auth-service ./backend/auth-service'
            }
        }
        
        stage('Test') {
            steps {
                // viết phần tests sau
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker stop auth-service || true'
                sh 'docker rm auth-service || true'
                sh 'docker run -d --name auth-service -p 8000:8000 storefront/auth-service'
            }
        }
    }
}